const cat = {
  openBackHeadphones: "openBackHeadphones",
  closedBackHeadphones: "closedBackHeadphones",
  overEarHeadphones: "overEarHeadphones",
  wirelessHeadphones: "wirelessHeadphones",
  planarIEM: "planarIEM",
  hybridIEM: "hybridIEM",
  dynamicIEM: "dynamicIEM",
  balanceArmatureIEM: "balanceArmatureIEM", 
  trueWirelessEarbuds: "trueWirelessEarbuds",
};
export const categories = [
  {
    _id: 1001,
    name: "Open Back Headphones",
    image: "http://localhost:8000/assets/itemAndLogo/baiem/ara.jpg",
    description:
      "Open-back headphones are a type of headphone that allows air to pass through the ear cups from the rear of the speaker driver.",
    _base: "openBackHeadphones",
  },
  {
    _id: 1002,
    name: "Closed Back Headphones",
    image: "https://i.ibb.co/71hR65V/catTvBox.webp",
    description:
      "Closed-back headphones are a type of headphone that completely seals the back of the ear cups, creating a closed chamber around the speaker driver. ",
    _base: "closedBackHeadphones",
  },
  {
    _id: 1003,
    name: "Over Ear Headphones",
    image: "https://i.ibb.co/71hR65V/catTvBox.webp",
    description:
      "Closed-back headphones are a type of headphone that completely seals the back of the ear cups, creating a closed chamber around the speaker driver. ",
    _base: "overEarHeadphones",
  },
  {
    _id: 1004,
    name: "Wireless Headphones",
    image: "https://i.ibb.co/0V0g6Gz/cat-Powertool.webp",
    description:
      "Wireless headphones offer the freedom to move around without the constraints of tangled wires. They connect to your devices via Bluetooth or other wireless technologies, allowing you to enjoy your music, podcasts, or calls without being tethered to a device.",
    _base: "wirelessHeadphones",
  },
  {
    _id: 1005,
    name: "Planar IEM",
    image: "https://i.ibb.co/zST2Xdp/cat-Headphone.webp",
    description:
      "Planar Magnetic IEMs offer a detailed and accurate sound with a wide soundstage. They use a large, flat diaphragm suspended between magnets to produce sound, resulting in a unique listening experience.",
    _base: "planarIEM",
  },
  {
    _id: 1006,
    name: "Hybrid IEM",
    image: "https://i.ibb.co/jgk59BL/catPhone.webp",
    description:
      "Hybrid IEMs combine multiple driver types, usually dynamic and balanced armature drivers, to achieve a balanced sound signature. This approach leverages the strengths of each driver type, often resulting in a more detailed and accurate sound than single-driver IEMs.",
    _base: "hybridIEM",
  },
  {
    _id: 1007,
    name: "Dynamic IEM",
    image: "https://i.ibb.co/B4NKfBZ/cat-Smart-Watch.webp",
    description:
      "Dynamic Driver IEMs are the most common type of IEMs, using a single dynamic driver to reproduce sound. They offer a warm, natural sound with good bass response, making them a popular choice for many listeners.",
    _base: "dynamicIEM",
  },
  {
    _id: 1008,
    name: "Balance Armature IEM",
    image: "https://i.ibb.co/4gwLwT2/cat-Gaming.webp",
    description:
      "Balanced armature (BA) IEMs are a type of in-ear monitor that uses a tiny, balanced armature driver to produce sound. This driver is incredibly efficient and capable of producing highly detailed and accurate sound. BA IEMs are known for their excellent clarity, detail retrieval, and fast transient response.",
    _base: "balanceArmatureIEM",
  },
  {
    _id: 1009,
    name: "True Wireless Earbuds",
    image: "https://i.ibb.co/4gwLwT2/cat-Gaming.webp",
    description:
      "True Wireless Earbuds are completely wireless, offering convenience and portability. They connect to your device via Bluetooth and come in various designs, from earbuds that fit entirely in your ear to those that rest on the outer ear.",
    _base: "trueWirelessEarbuds",
  },
];

export const products = [
  {
    _id: 2001,
    name: "Campfire Audio Ara",
    images: [
      "http://localhost:8000/assets/itemAndLogo/baiem/ara.jpg",
      "http://localhost:8000/assets/itemAndLogo/frgraphs/bagraph/arag.jpg",
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 600,
    discountedPrice: 580,
    quantity: 1,
    rating: 4.5,
    reviews: 50,
    category: "Balance Armature IEM",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Campfire Audio",
    isStock: true,
    overView: "Balance Armature IEM",
    isNew: true,
    _base: cat?.balanceArmatureIEM,
  },
  {
    _id: 2002,
    name: "Nocturnal Audio Atlantis",
    images: [
      "http://localhost:8000/assets/itemAndLogo/baiem/atlantis.jpg",
      "http://localhost:8000/assets/itemAndLogo/frgraphs/bagraph/atlantisg.jpg"
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 250,
    discountedPrice: 180,
    quantity: 1,
    rating: 4.8,
    reviews: 80,
    category: "Balance Armature IEM",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Nocturnal Audio",
    isStock: true,
    overView: "Balance Armature IEM",
    isNew: false,
    _base: cat?.balanceArmatureIEM,
  },
  {
    _id: 2003,
    name: "Dunu SA6 MKII",
    images: [
      "http://localhost:8000/assets/itemAndLogo/baiem/dunusa6mkii.webp",
      "http://localhost:8000/assets/itemAndLogo/frgraphs/bagraph/sa6mkiig.jpg"
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 650,
    discountedPrice: 570,
    quantity: 1,
    rating: 4.2,
    reviews: 30,
    category: "Balance Armature IEM",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Dunu",
    isStock: true,
    overView: "Balance Armature IEM",
    isNew: true,
    _base: cat?.balanceArmatureIEM,
  },
  {
    _id: 2004,
    name: "Sony M7",
    images: [
      "http://localhost:8000/assets/itemAndLogo/baiem/m7.jpg",
      "http://localhost:8000/assets/itemAndLogo/frgraphs/bagraph/m7g.jpg"
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 400,
    discountedPrice: 350,
    quantity: 1,
    rating: 4.2,
    reviews: 120,
    category: "Balance Armature IEM",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Sony",
    isStock: false,
    overView: "Balance Armature IEM",
    isNew: false,
    _base: cat?.balanceArmatureIEM,
  },
  {
    _id: 2005,
    name: "Fearless Audio S8Z",
    images: [
      "http://localhost:8000/assets/itemAndLogo/baiem/s8z.jpg",
      "http://localhost:8000/assets/itemAndLogo/frgraphs/bagraph/s8zg.jpg"
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 90,
    discountedPrice: 80,
    quantity: 1,
    rating: 4.2,
    reviews: 20,
    category: "Balance Armature IEM",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Fearless Audio",
    isStock: true,
    overView: "Balance Armature IEM",
    isNew: true,
    _base: cat?.balanceArmatureIEM,
  },
  {
    _id: 2006,
    name: "Moondrop Chu",
    images: [
      "http://localhost:8000/assets/itemAndLogo/diem/chu.jpg",
      "http://localhost:8000/assets/itemAndLogo/frgraphs/dgraph/chug.jpg"
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 300,
    discountedPrice: 280,
    quantity: 1,
    rating: 4.8,
    reviews: 110,
    category: "Dynamic IEM",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Moondrop",
    isStock: true,
    overView: "Dynamic IEM",
    isNew: false,
    _base: cat.dynamicIEM,
  },
  {
    _id: 2007,
    name: "Dunu Luna",
    images: [
      "http://localhost:8000/assets/itemAndLogo/diem/luna.png",
      "http://localhost:8000/assets/itemAndLogo/frgraphs/dgraph/lunag.jpg"
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 600,
    discountedPrice: 550,
    quantity: 1,
    rating: 4,
    reviews: 60,
    category: "Dynamic IEM",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Dunu",
    isStock: true,
    overView: "Dynamic IEM",
    isNew: true,
    _base: cat.dynamicIEM,
  },
  {
    _id: 2008,
    name: "Tanchjim Origin",
    images: [
      "http://localhost:8000/assets/itemAndLogo/diem/origin.jpg",
      "http://localhost:8000/assets/itemAndLogo/frgraphs/dgraph/origing.jpg"
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 1100,
    discountedPrice: 1080,
    quantity: 1,
    rating: 4.7,
    reviews: 190,
    category: "Dynamic IEM",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Tanchjim",
    isStock: true,
    overView: "Dynamic IEM",
    isNew: false,
    _base: cat?.dynamicIEM,
  },
  {
    _id: 2009,
    name: "Softears Turii",
    images: [
      "http://localhost:8000/assets/itemAndLogo/diem/turii.jpg",
      "http://localhost:8000/assets/itemAndLogo/frgraphs/dgraph/turiig.jpg"
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 450,
    discountedPrice: 380,
    quantity: 1,
    rating: 4.2,
    reviews: 70,
    category: "Dynamic IEM",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Softears",
    isStock: true,
    overView: "Dynamic IEM",
    isNew: true,
    _base: cat?.dynamicIEM,
  },
  {
    _id: 2010,
    name: "Sennheiser HD600",
    images: [
      "http://localhost:8000/assets/itemAndLogo/over_ear/hd600.webp",
      "http://localhost:8000/assets/itemAndLogo/frgraphs/oegraph/hd600g.jpg"
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 305,
    discountedPrice: 285,
    quantity: 1,
    rating: 4.1,
    reviews: 160,
    category: "Over Ear Headphones",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Sennheiser",
    isStock: true,
    overView: "Over Ear Headphones",
    isNew: true,
    _base: cat?.overEarHeadphones,
  },
  {
    _id: 2011,
    name: "Sennheiser HD800S",
    images: [
      "http://localhost:8000/assets/itemAndLogo/over_ear/hd800s.webp",
      "http://localhost:8000/assets/itemAndLogo/frgraphs/oegraph/hd800sg.jpg"
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 350,
    discountedPrice: 280,
    quantity: 1,
    rating: 3.8,
    reviews: 250,
    category: "Over Ear Headphones",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Sennheiser",
    isStock: true,
    overView: "Over Ear Headphones",
    isNew: true,
    _base: cat?.overEarHeadphones,
  },
  {
    _id: 2012,
    name: "Focal Bathys",
    images: [
      "http://localhost:8000/assets/itemAndLogo/over_ear/bathys.webp",
      "http://localhost:8000/assets/itemAndLogo/frgraphs/oegraph/bathysg.jpg"
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 150,
    discountedPrice: 80,
    quantity: 1,
    rating: 4.7,
    reviews: 90,
    category: "Over Ear Headphones",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Focal",
    isStock: true,
    overView: "Over Ear Headphones",
    isNew: true,
    _base: cat?.overEarHeadphones,
  },
  {
    _id: 2013,
    name: "Hifiman Sundara",
    images: [
      "http://localhost:8000/assets/itemAndLogo/over_ear/sundarav2.webp",
      "http://localhost:8000/assets/itemAndLogo/frgraphs/oegraph/sundarag.jpg"
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 210,
    discountedPrice: 200,
    quantity: 1,
    rating: 3.9,
    reviews: 100,
    category: "Over Ear Headphones",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Hifiman",
    isStock: true,
    overView: "Over Ear Headphones",
    isNew: true,
    _base: cat?.overEarHeadphones,
  },
  {
    _id: 2014,
    name: "Beyerdynamic DT1990 Pro",
    images: [
      "http://localhost:8000/assets/itemAndLogo/over_ear/dt1990pro.webp",
      "http://localhost:8000/assets/itemAndLogo/frgraphs/oegraph/dt1990prog.jpg"
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 80,
    discountedPrice: 75,
    quantity: 1,
    rating: 4.2,
    reviews: 110,
    category: "Over Ear Headphones",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Beyerdynamic",
    isStock: true,
    overView: "Over Ear Headphones",
    isNew: true,
    _base: cat?.overEarHeadphones,
  },
  {
    _id: 2015,
    name: "Shure Aonic 50",
    images: [
      "http://localhost:8000/assets/itemAndLogo/wireless/aonic.webp",
      "http://localhost:8000/assets/itemAndLogo/frgraphs/wirelessgraph/aonicg.jpg"
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 560,
    discountedPrice: 400,
    quantity: 1,
    rating: 4,
    reviews: 300,
    category: "Wireless Headphones",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Shure",
    isStock: true,
    overView: "Wireless Headphones",
    isNew: true,
    _base: cat?.wirelessHeadphones,
  },
  {
    _id: 2016,
    name: "Sennheiser Momentum 4",
    images: [
      "http://localhost:8000/assets/itemAndLogo/wireless/momentum.webp",
      "http://localhost:8000/assets/itemAndLogo/frgraphs/wirelessgraph/momentumg.jpg"
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 250,
    discountedPrice: 240,
    quantity: 1,
    rating: 4.2,
    reviews: 110,
    category: "Wireless Headphones",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Sennheiser",
    isStock: true,
    overView: "Wireless Headphones",
    isNew: true,
    _base: cat?.wirelessHeadphones,
  },
  {
    _id: 2017,
    name: "Sony WH-1000XM5",
    images: [
      "http://localhost:8000/assets/itemAndLogo/wireless/sony.webp",
      "http://localhost:8000/assets/itemAndLogo/frgraphs/wirelessgraph/sonyg.jpg"
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 60,
    discountedPrice: 55,
    quantity: 1,
    rating: 4,
    reviews: 100,
    category: "Wireless Headphones",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Sony",
    isStock: true,
    overView: "Wireless Headphones",
    isNew: true,
    _base: cat?.wirelessHeadphones,
  },
  {
    _id: 2018,
    name: "B&W PX",
    images: [
      "http://localhost:8000/assets/itemAndLogo/wireless/px.jpg",
      "http://localhost:8000/assets/itemAndLogo/frgraphs/wirelessgraph/pxg.jpg"
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 350,
    discountedPrice: 330,
    quantity: 1,
    rating: 4.2,
    reviews: 70,
    category: "Wireless Headphones",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "B&W",
    isStock: true,
    overView: "Wireless Headphones",
    isNew: true,
    _base: cat?.wirelessHeadphones,
  },
  {
    _id: 2019,
    name: "B&O BeoPlay H7",
    images: [
      "http://localhost:8000/assets/itemAndLogo/wireless/h7.webp",
      "http://localhost:8000/assets/itemAndLogo/frgraphs/wirelessgraph/h7g.jpg"
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 120,
    discountedPrice: 100,
    quantity: 1,
    rating: 4.1,
    reviews: 20,
    category: "Wireless Headphones",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "B&O",
    isStock: true,
    overView: "Wireless Headphones",
    isNew: true,
    _base: cat?.wirelessHeadphones,
  },
  {
    _id: 2020,
    name: "Dita Dream XLS",
    images: [
      "http://localhost:8000/assets/itemAndLogo/diem/xls.webp",
      "http://localhost:8000/assets/itemAndLogo/frgraphs/dgraph/xlsg.jpg"
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 450,
    discountedPrice: 410,
    quantity: 1,
    rating: 3.7,
    reviews: 190,
    category: "Dynamic IEM",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Dita",
    isStock: true,
    overView: "Dynamic IEM",
    isNew: true,
    _base: cat?.dynamicIEM,
  },
  {
    _id: 2021,
    name: "Elysian X",
    images: [
      "http://localhost:8000/assets/itemAndLogo/hybridiem/x.webp",
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 350,
    discountedPrice: 320,
    quantity: 1,
    rating: 3.9,
    reviews: 10,
    category: "Hybrid IEM",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Dita",
    isStock: true,
    overView: "Hybrid IEM",
    isNew: true,
    _base: cat?.hybridIEM,
  },
  {
    _id: 2022,
    name: "Empire Ears Legend EVO",
    images: [
      "http://localhost:8000/assets/itemAndLogo/hybridiem/evo.webp",
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 250,
    discountedPrice: 240,
    quantity: 1,
    rating: 4.2,
    reviews: 100,
    category: "Hybrid IEM",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Empire Ears",
    isStock: true,
    overView: "Hybrid IEM",
    isNew: true,
    _base: cat?.hybridIEM,
  },
  {
    _id: 2023,
    name: "Empire Ears Nemesis",
    images: [
      "http://localhost:8000/assets/itemAndLogo/hybridiem/nemesis.webp",
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 600,
    discountedPrice: 580,
    quantity: 1,
    rating: 4.7,
    reviews: 200,
    category: "Hybrid IEM",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Empire Ears",
    isStock: true,
    overView: "Hybrid IEM",
    isNew: true,
    _base: cat?.hybridIEM,
  },
  {
    _id: 2024,
    name: "Etymotic ER4SR",
    images: [
      "http://localhost:8000/assets/itemAndLogo/baiem/ety.webp",
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 80,
    discountedPrice: 70,
    quantity: 1,
    rating: 4.2,
    reviews: 60,
    category: "Balance Armature IEM",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Etymotic",
    isStock: true,
    overView: "Balance Armature IEM",
    isNew: true,
    _base: cat?.balanceArmatureIEM,
  },
  {
    _id: 2025,
    name: "Final Audio A8000",
    images: [
      "http://localhost:8000/assets/itemAndLogo/diem/a8000.webp",
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Dynamic IEM",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Final Audio",
    isStock: true,
    overView: "Dynamic IEM",
    isNew: true,
    _base: cat?.dynamicIEM,
  },
  {
    _id: 2026,
    name: "Dunu Falcon Pro",
    images: [
      "http://localhost:8000/assets/itemAndLogo/diem/falconPro.webp",
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 290,
    discountedPrice: 130,
    quantity: 1,
    rating: 4.2,
    reviews: 30,
    category: "Dynamic IEM",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Dunu",
    isStock: true,
    overView: "Dynamic IEM",
    isNew: true,
    _base: cat?.dynamicIEM,
  },
  {
    _id: 2027,
    name: "Jomo Trinity",
    images: [
      "http://localhost:8000/assets/itemAndLogo/hybridiem/trinity.jpg",
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 660,
    discountedPrice: 630,
    quantity: 1,
    rating: 3.5,
    reviews: 50,
    category: "Hybrid IEM",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Jomo",
    isStock: true,
    overView: "Hybrid IEM",
    isNew: true,
    _base: cat?.hybridIEM,
  },
  {
    _id: 2028,
    name: "JVC HA-FW10000",
    images: [
      "http://localhost:8000/assets/itemAndLogo/diem/jvc.jpg",
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 500,
    discountedPrice: 445,
    quantity: 1,
    rating: 4.8,
    reviews: 190,
    category: "Dynamic IEM",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "JVC",
    isStock: true,
    overView: "Dynamic IEM",
    isNew: true,
    _base: cat?.dynamicIEM,
  },
  {
    _id: 2029,
    name: "Thieaudio Wraith",
    images: [
      "http://localhost:8000/assets/itemAndLogo/openBack/wraith.webp",
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 820,
    discountedPrice: 810,
    quantity: 1,
    rating: 4.6,
    reviews: 90,
    category: "Open Back Headphone",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Thieaudio",
    isStock: true,
    overView: "Open Back Headphone",
    isNew: true,
    _base: cat?.openBackHeadphones,
  },
  {
    _id: 2030,
    name: "Meze Audio Elite",
    images: [
      "http://localhost:8000/assets/itemAndLogo/openBack/elite.webp",
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 270,
    discountedPrice: 250,
    quantity: 1,
    rating: 4.5,
    reviews: 220,
    category: "Open Back Headphone",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Meze",
    isStock: true,
    overView: "Open Back Headphone",
    isNew: true,
    _base: cat?.openBackHeadphones,
  },
  {
    _id: 2031,
    name: "Fostex TH909",
    images: [
      "http://localhost:8000/assets/itemAndLogo/closedBack/th909.jpg",
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 120,
    discountedPrice: 100,
    quantity: 1,
    rating: 4.0,
    reviews: 120,
    category: "Closed Back Headphone",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Fostex",
    isStock: true,
    overView: "Closed Back Headphone",
    isNew: true,
    _base: cat?.closedBackHeadphones,
  },
  {
    _id: 2032,
    name: "Sony MDR-Z1R",
    images: [
      "http://localhost:8000/assets/itemAndLogo/closedBack/mdrz1r.jpg",
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 520,
    discountedPrice: 510,
    quantity: 1,
    rating: 4.5,
    reviews: 70,
    category: "Closed Back Headphone",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Sony",
    isStock: true,
    overView: "Closed Back Headphone",
    isNew: true,
    _base: cat?.closedBackHeadphones,
  },
  {
    _id: 2033,
    name: "Meze 99 Classics",
    images: [
      "http://localhost:8000/assets/itemAndLogo/closedBack/99classic.png",
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 100,
    discountedPrice: 80,
    quantity: 1,
    rating: 3.9,
    reviews: 110,
    category: "Closed Back Headphone",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Meze",
    isStock: true,
    overView: "Closed Back Headphone",
    isNew: true,
    _base: cat?.closedBackHeadphones,
  },
  {
    _id: 2034,
    name: "Audio Technica ATH-AWKT",
    images: [
     "http://localhost:8000/assets/itemAndLogo/closedBack/awkt.webp",
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 200,
    discountedPrice: 100,
    quantity: 1,
    rating: 4.3,
    reviews: 150,
    category: "Closed Back Headphone",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Audio Technica",
    isStock: true,
    overView: "Closed Back Headphone",
    isNew: true,
    _base: cat?.closedBackHeadphones,
  },
  {
    _id: 2035,
    name: "Hifiman HE1000se",
    images: [
      "http://localhost:8000/assets/itemAndLogo/openBack/he1000.webp",
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 1000,
    discountedPrice: 810,
    quantity: 1,
    rating: 3.2,
    reviews: 55,
    category: "Open Back Headphone",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Hifiman",
    isStock: true,
    overView: "Open Back Headphone",
    isNew: true,
    _base: cat?.openBackHeadphones,
  },
  {
    _id: 2036,
    name: "Stax SR-009s",
    images: [
      "http://localhost:8000/assets/itemAndLogo/openBack/stax.jpg",
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 720,
    discountedPrice: 510,
    quantity: 1,
    rating: 4.4,
    reviews: 80,
    category: "Open Back Headphone",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Stax",
    isStock: true,
    overView: "Open Back Headphone",
    isNew: true,
    _base: cat?.openBackHeadphones,
  },
  {
    _id: 2037,
    name: "Oriolus Szalayi",
    images: [
      "http://localhost:8000/assets/itemAndLogo/planariem/szalayi.jpg",
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 620,
    discountedPrice: 550,
    quantity: 1,
    rating: 4.5,
    reviews: 250,
    category: "Planar IEM",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Oriolus",
    isStock: true,
    overView: "Planar IEM",
    isNew: true,
    _base: cat?.planarIEM,
  },
  {
    _id: 2038,
    name: "Moondrop Stellaris",
    images: [
      "http://localhost:8000/assets/itemAndLogo/planariem/stellaris.jpg",
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 160,
    discountedPrice: 110,
    quantity: 1,
    rating: 4.8,
    reviews: 130,
    category: "Planar IEM",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Moondrop",
    isStock: true,
    overView: "Planar IEM",
    isNew: true,
    _base: cat?.planarIEM,
  },
  {
    _id: 2039,
    name: "Audeze Euclid",
    images: [
      "http://localhost:8000/assets/itemAndLogo/planariem/euclid.webp",
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 120,
    discountedPrice: 110,
    quantity: 1,
    rating: 4.0,
    reviews: 190,
    category: "Planar IEM",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Audeze",
    isStock: true,
    overView: "Planar IEM",
    isNew: true,
    _base: cat?.planarIEM,
  },
  {
    _id: 2040,
    name: "Letshuoer S12",
    images: [
      "http://localhost:8000/assets/itemAndLogo/planariem/s12.webp",
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 50,
    discountedPrice: 20,
    quantity: 1,
    rating: 2.5,
    reviews: 90,
    category: "Planar IEM",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Letshuoer",
    isStock: true,
    overView: "Planar IEM",
    isNew: true,
    _base: cat?.planarIEM,
  },
  {
    _id: 2041,
    name: "Master & Dynamic MW07",
    images: [
      "http://localhost:8000/assets/itemAndLogo/tws/mw07.jpg",
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 800,
    discountedPrice: 510,
    quantity: 1,
    rating: 4.9,
    reviews: 100,
    category: "True Wireless Earbuds",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Master&Dynamic",
    isStock: true,
    overView: "True Wireless Earbuds",
    isNew: true,
    _base: cat?.trueWirelessEarbuds,
  },
  {
    _id: 2042,
    name: "Noble Falcon",
    images: [
      "http://localhost:8000/assets/itemAndLogo/tws/nobleFalcon.jpg",
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 2520,
    discountedPrice: 2310,
    quantity: 1,
    rating: 4.5,
    reviews: 80,
    category: "True Wireless Earbuds",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Noble Audio",
    isStock: true,
    overView: "True Wireless Earbuds",
    isNew: true,
    _base: cat?.trueWirelessEarbuds,
  },
  {
    _id: 2043,
    name: "Lypertek Tevi",
    images: [
      "http://localhost:8000/assets/itemAndLogo/tws/tevi.jpg",
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 520,
    discountedPrice: 410,
    quantity: 1,
    rating: 4.2,
    reviews: 30,
    category: "True Wireless Earbuds",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Lypertek",
    isStock: true,
    overView: "True Wireless Earbuds",
    isNew: true,
    _base: cat?.trueWirelessEarbuds,
  },
  {
    _id: 2044,
    name: "Nuarl NT100",
    images: [
      "http://localhost:8000/assets/itemAndLogo/tws/nuarl.jpg",
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 400,
    discountedPrice: 400,
    quantity: 1,
    rating: 4.5,
    reviews: 50,
    category: "True Wireless Earbuds",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Nuarl",
    isStock: true,
    overView: "True Wireless Earbuds",
    isNew: true,
    _base: cat?.trueWirelessEarbuds,
  },
  {
    _id: 2045,
    name: "Sony WF-1000XM3",
    images: [
      "http://localhost:8000/assets/itemAndLogo/tws/1000xm3.png",
    ],
    description:
      "Immerse yourself in your favorite music with our high-quality headphones and IEMs. Experience rich sound, powerful bass, and crystal-clear highs.",
    regularPrice: 620,
    discountedPrice: 550,
    quantity: 1,
    rating: 4.6,
    reviews: 135,
    category: "True Wireless Earbuds",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Sony",
    isStock: true,
    overView: "True Wireless Earbuds",
    isNew: true,
    _base: cat?.trueWirelessEarbuds,
  },
];
